# 创建服务
apiVersion: v1
kind: Service
metadata:
  name: ${CI_ENVIRONMENT_NAME}-${CI_PROJECT_PATH_SLUG}
spec:
  selector:
    app: ${CI_ENVIRONMENT_NAME}-${CI_PROJECT_PATH_SLUG}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
# 部署应用
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${CI_ENVIRONMENT_NAME}-${CI_PROJECT_PATH_SLUG}
spec:
  selector:
    matchLabels:
      app: ${CI_ENVIRONMENT_NAME}-${CI_PROJECT_PATH_SLUG}
  replicas: 1
  template:
    metadata:
      labels:
        app: ${CI_ENVIRONMENT_NAME}-${CI_PROJECT_PATH_SLUG}
    spec:
      containers:
        - name: nginx
          image: reg.haochang.tv/library/${CI_PROJECT_PATH}/nginx:${CI_PIPELINE_ID}
          ports:
            - containerPort: 80
          readinessProbe: ##kubernetes health check
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 3 
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 5
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-config
          configMap:
            name: ${CI_ENVIRONMENT_NAME}-${CI_PROJECT_PATH_SLUG}-nginx-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${CI_ENVIRONMENT_NAME}-${CI_PROJECT_PATH_SLUG}-nginx-config
data:
  default.conf: |
    server {
        listen       80;                                                    
        server_name  localhost;
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            error_page 404 =200 /index.html;
        }
    }
